name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]  # Or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload static files from Project_1
      uses: actions/upload-pages-artifact@v2
      with:
        path: './Project_1'  # 👈 this is the important fix

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
