name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # upgraded from v2

      # Optional: setup Node.js if you're using npm/yarn build steps
      # Remove if you're just using plain HTML/CSS
      # - name: Setup Node.js (optional)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Project_1  # 👈 specify the folder where index.html lives
